### ISSUE TITLE
Feauture: Add Favorite, Recently Used to Application Menu (plugin-menu)

### ISSUE THREAD

**Issue by ibroheem** [lxde/lxde.github.io#31] opened 2017-01-06 17:15 UTC
Addition of Favorites, Recently Used to Application Menu (plugin-menu) as found in Plasma, XFCE4 (whisker menu)

**Comment by pmattern** [comment] 2017-01-07 19:42
Duplicate of lxde/lxqt#100, also discussed in lxde/lxqt#1196.

That aside please note that this tracker is addressing the homepage lxqt.org, the panel is covered by https://github.com/lxde/lxqt/issues.

**Closed by pmattern** 2017-01-07 19:42 UTC

**Comment by ibroheem** [comment] 2017-01-07 21:47
Thanks, never saw that.

**Comment by pmattern** [comment] 2017-01-07 23:07
You're welcome.
